name = "route-sync"
compatibility_date = "2025-09-12"

# Entry point
main = "src/index.js"

# D1 binding
[[d1_databases]]
binding = "RouteDB"
database_name = "RouteDB"
database_id = "82bada57-e637-4f07-afae-1db9d18078aa"

[observability.logs]
enabled = true



